# Generated by Django 5.0 on 2024-02-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('trip', models.CharField(max_length=100)),
                ('trip_duration', models.TimeField()),
                ('conductor', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=50)),
            ],
        ),
    ]
